# -----------------------
# Server 1
# -----------------------
server {
    listen 0.0.0.0:8080;
    listen 127.0.0.1:1025;

    client_max_body_size 5m;

    error_page 404 /404.html;
    error_page 500 /500.html;
}

# # -----------------------
# # Server 2
# # -----------------------
# server {
#     listen 192.168.1.100:8081;
#     listen 0.0.0.0:8082;

#     client_max_body_size 10m;

#     error_page 403 /403.html;
#     error_page 502 /502.html;

# }

# # -----------------------
# # Server 3
# # -----------------------
# server {
#     listen 10.0.0.5:9090;

#     client_max_body_size 20m;

#     error_page 404 /notfound.html;

# }